exports.array = [
    'components/dark-light/DarkLightBottombar.htm resources/js/components/dark-light/',
    'components/dark-light/DarkLightBottombar.vue resources/js/components/dark-light/',
    'components/dark-light/DarkLightNavbar.htm resources/js/components/dark-light/',
    'components/dark-light/DarkLightNavbar.vue resources/js/components/dark-light/',
    'components/dark-light/DarkLightTopbar.htm resources/js/components/dark-light/',
    'components/dark-light/DarkLightTopbar.vue resources/js/components/dark-light/',

    'pages/market/history.htm resources/js/pages/market',
    'pages/market/history.vue resources/js/pages/market',
    'pages/market/limit-buy.htm resources/js/pages/market',
    'pages/market/limit-buy.vue resources/js/pages/market',
    'pages/market/limit-sell.htm resources/js/pages/market',
    'pages/market/limit-sell.vue resources/js/pages/market',
    'pages/market/my-history.htm resources/js/pages/market',
    'pages/market/my-history.vue resources/js/pages/market',
    'pages/market/my-orders.htm resources/js/pages/market',
    'pages/market/my-orders.vue resources/js/pages/market',
    'pages/market/orderbook.htm resources/js/pages/market',
    'pages/market/orderbook.vue resources/js/pages/market',
    'pages/market/quick-buy.htm resources/js/pages/market',
    'pages/market/quick-buy.vue resources/js/pages/market',
    'pages/market/quick-sell.htm resources/js/pages/market',
    'pages/market/quick-sell.vue resources/js/pages/market',
    'pages/market-inner.htm resources/js/pages',
    'pages/market-inner.vue resources/js/pages',

    'layouts/market.vue resources/js/layouts',

];