<?php

namespace Tests\Feature\Jobs;

use App\Jobs\Wallets\CreateUserWallets;
use App\Models\Wallet;
use App\User;
use Tests\ApiTestCase;

class CreateUserWalletsTest extends ApiTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed('CurrenciesTableSeeder');
    }

    public function testCreateUserWallets()
    {
        $user = $this->createUser();

        $job = new CreateUserWallets($user);
        $job->handle();

        //Check if wallets created
        $this->assertDatabaseHas('wallets', ['user_id' => $user['id'], 'currency_id' => 1]);
    }
}
