<?php

namespace Tests\Feature\Jobs;

use App\Jobs\Wallets\CreateUserFiatWallets;
use App\Models\Wallet;
use App\User;
use Tests\ApiTestCase;

class CreateUserFiatWalletsTest extends ApiTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed('FiatCurrenciesTableSeeder');
    }

    public function testCreateUserFiatWallets()
    {
        $user = $this->createUser();

        $job = new CreateUserFiatWallets($user);
        $job->handle();

        //Check if wallets created
        $this->assertDatabaseHas('fiat_wallets', ['user_id' => $user->id, 'fiat_currency_id' => 1]);
    }
}
